
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const VEN_CLIENT_CHARGE_ACCOUNT = 'VEN_CLIENT_CHARGE_ACCOUNT';
export const VEN_CLIENT_GET_TRANSACTIONS_LIST = 'VEN_CLIENT_GET_TRANSACTIONS_LIST';
export const VEN_CLIENT_GET_DETAILS = 'VEN_CLIENT_GET_DETAILS';
export const VEN_CLIENT_CHECK_PENDING_PAYMENTS = 'VEN_CLIENT_CHECK_PENDING_PAYMENTS';
export const VEN_CLIENT_APPROVE_PAYMENT_TRANSFER = 'VEN_CLIENT_APPROVE_PAYMENT_TRANSFER';

export const VEN_COMERCIO_GET_TRANSACTIONS_LIST = 'VEN_COMERCIO_GET_TRANSACTIONS_LIST';
export const VEN_COMERCIO_ADD_PAYMENT_REQUEST = 'VEN_COMERCIO_ADD_PAYMENT_REQUEST';
export const VEN_COMERCIO_GET_DETAILS = 'VEN_COMERCIO_GET_DETAILS';

export const VEN_CONTROL_GET_DETAILS = 'VEN_CONTROL_GET_DETAILS';
export const VEN_CONTROL_GET_TRANSACTIONS_LIST = 'VEN_CONTROL_GET_TRANSACTIONS_LIST';
export const VEN_CONTROL_GENERATE_CODE = 'VEN_CONTROL_GENERATE_CODE';

export const VEN_LOCAL_SHOW_USER_INFO = 'VEN_LOCAL_SHOW_USER_INFO';
export const VEN_LOCAL_SAVE_PROFILE_IMAGE = 'VEN_LOCAL_SAVE_PROFILE_IMAGE';


//denisa
export const VEN_UPDATE_USER_INFO_INIT = 'VEN_UPDATE_USER_INFO_INIT';
export const VEN_UPDATE_USER_INFO_SUCCESS = 'VEN_UPDATE_USER_INFO_SUCCESS';
export const VEN_UPDATE_USER_INFO_ERROR = 'VEN_UPDATE_USER_INFO_FAIL';




// new actionsTypes used:

export const VEN_SIGNUP = 'VEN_SIGNUP';
export const VEN_LOGIN = 'VEN_LOGIN';

export const VEN_GENERATE_TRANSFER_CODE = 'VEN_GENERATE_TRANSFER_CODE';
export const VEN_GET_ALL_TRANSACTIONS = 'VEN_GET_ALL_TRANSACTIONS';
export const VEN_GET_EXCHANGE_RATE = 'VEN_GET_EXCHANGE_RATE';
export const VEN_EXCHANGE_CURRENCIES = 'VEN_EXCHANGE_CURRENCIES';
export const VEN_UPDATE_BALLANCE = 'VEN_UPDATE_BALLANCE';
export const VEN_RECHARGE_BALLANCE = 'VEN_RECHARGE_BALLANCE';


export const VEN_REQUEST_PAYMENT = 'VEN_REQUEST_PAYMENT';

